# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0}]

# IP: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0}]

# IP: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0}]

# IP: bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_1 || ORIG_REF_NAME==design_1_ilmb_v10_1}]

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0}]

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_1}]

# IP: bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0}]

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_0}]

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0}]

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_0/design_1_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_0}]

# IP: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0}]

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0}]

# IP: bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_timer_0_0 || ORIG_REF_NAME==design_1_axi_timer_0_0}]

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}]

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1}]

# IP: bd/design_1/ip/design_1_axi_mem_intercon_1/design_1_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_1}]

# IP: bd/design_1/ip/design_1_axi_ethernet_0_0/design_1_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_0}]

# Block Designs: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/bd_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0}]

# IP: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}]

# IP: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_1/bd_0_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}]

# IP: bd/design_1/ip/design_1_axi_ethernet_0_dma_0/design_1_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_dma_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_dma_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1}]

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/design_1_trigger_logic_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_trigger_logic_AXI_0_0 || ORIG_REF_NAME==design_1_trigger_logic_AXI_0_0}]

# IP: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/c_counter_binary_3/c_counter_binary_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_3 || ORIG_REF_NAME==c_counter_binary_3}]

# IP: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/prescaler_counter_binary_3/prescaler_counter_binary_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prescaler_counter_binary_3 || ORIG_REF_NAME==prescaler_counter_binary_3}]

# IP: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/c_counter_binary_2/c_counter_binary_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_2 || ORIG_REF_NAME==c_counter_binary_2}]

# IP: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/c_counter_binary_1/c_counter_binary_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_1 || ORIG_REF_NAME==c_counter_binary_1}]

# IP: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_0 || ORIG_REF_NAME==c_counter_binary_0}]

# IP: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1}]

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_401M_0/design_1_rst_clk_wiz_0_401M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_401M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_401M_0}]

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_125M_0/design_1_rst_clk_wiz_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_125M_0}]

# IP: bd/design_1/ip/design_1_real_time_clock_v1_0_S00_AXI_0_0/design_1_real_time_clock_v1_0_S00_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_real_time_clock_v1_0_S00_AXI_0_0 || ORIG_REF_NAME==design_1_real_time_clock_v1_0_S00_AXI_0_0}]

# IP: bd/design_1/ip/design_1_real_time_clock_v1_0_S00_AXI_0_0/ip/real_time_1ms_from_125MHz_counter_0/real_time_1ms_from_125MHz_counter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==real_time_1ms_from_125MHz_counter_0 || ORIG_REF_NAME==real_time_1ms_from_125MHz_counter_0}]

# IP: bd/design_1/ip/design_1_real_time_clock_v1_0_S00_AXI_0_0/ip/real_time_32b_counter_0/real_time_32b_counter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==real_time_32b_counter_0 || ORIG_REF_NAME==real_time_32b_counter_0}]

# IP: bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0}]

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0}]

# IP: bd/design_1/ip/design_1_phase_shift_40MHz_clk_gen_axi_0_1/design_1_phase_shift_40MHz_clk_gen_axi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_phase_shift_40MHz_clk_gen_axi_0_1 || ORIG_REF_NAME==design_1_phase_shift_40MHz_clk_gen_axi_0_1}]

# IP: bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_0 || ORIG_REF_NAME==design_1_s00_data_fifo_0}]

# IP: bd/design_1/ip/design_1_s01_data_fifo_0/design_1_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s01_data_fifo_0 || ORIG_REF_NAME==design_1_s01_data_fifo_0}]

# IP: bd/design_1/ip/design_1_s02_data_fifo_0/design_1_s02_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s02_data_fifo_0 || ORIG_REF_NAME==design_1_s02_data_fifo_0}]

# IP: bd/design_1/ip/design_1_s03_data_fifo_0/design_1_s03_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s03_data_fifo_0 || ORIG_REF_NAME==design_1_s03_data_fifo_0}]

# IP: bd/design_1/ip/design_1_s04_data_fifo_0/design_1_s04_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s04_data_fifo_0 || ORIG_REF_NAME==design_1_s04_data_fifo_0}]

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0}]

# IP: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1}]

# IP: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2}]

# XDC: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc

# XDC: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0}]

# XDC: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0}]

# XDC: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_1 || ORIG_REF_NAME==design_1_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_ilmb_v10_1/design_1_ilmb_v10_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/design_1_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc

# XDC: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0}]

# XDC: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0}]

# XDC: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_timer_0_0 || ORIG_REF_NAME==design_1_axi_timer_0_0}]

# XDC: bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_buf_0 || ORIG_REF_NAME==bd_0_eth_buf_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0_eth_buf_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0_eth_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0_eth_mac_0 || ORIG_REF_NAME==bd_0_eth_mac_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/bd_0/bd_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_0/synth/design_1_axi_ethernet_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_dma_0/design_1_axi_ethernet_0_dma_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_dma_0/design_1_axi_ethernet_0_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_dma_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_ethernet_0_dma_0/design_1_axi_ethernet_0_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_dma_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_dma_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/c_counter_binary_3/c_counter_binary_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/prescaler_counter_binary_3/prescaler_counter_binary_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/c_counter_binary_2/c_counter_binary_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/c_counter_binary_1/c_counter_binary_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_trigger_logic_AXI_0_0/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: ipshared/user.org/trigger_logic_axi_v1_1/d31798e6/constrs_1/imports/new/ac701_trigger_logic_design.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_trigger_logic_AXI_0_0 || ORIG_REF_NAME==design_1_trigger_logic_AXI_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_0_401M_0/design_1_rst_clk_wiz_0_401M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_401M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_401M_0}]

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_0_401M_0/design_1_rst_clk_wiz_0_401M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_401M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_401M_0}]

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_0_401M_0/design_1_rst_clk_wiz_0_401M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_0_125M_0/design_1_rst_clk_wiz_0_125M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_125M_0}]

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_0_125M_0/design_1_rst_clk_wiz_0_125M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_125M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_125M_0}]

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_0_125M_0/design_1_rst_clk_wiz_0_125M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_real_time_clock_v1_0_S00_AXI_0_0/ip/real_time_1ms_from_125MHz_counter_0/real_time_1ms_from_125MHz_counter_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_real_time_clock_v1_0_S00_AXI_0_0/ip/real_time_32b_counter_0/real_time_32b_counter_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: ipshared/user.org/phase_shift_40mhz_clk_gen_axi_v1_0/db1dbbe0/phase_shift_40MHz_clk_gen_axi.srcs/constrs_1/new/phase_shift_40MHz_clk_constraints.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_phase_shift_40MHz_clk_gen_axi_0_1 || ORIG_REF_NAME==design_1_phase_shift_40MHz_clk_gen_axi_0_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s01_data_fifo_0/design_1_s01_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s02_data_fifo_0/design_1_s02_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s03_data_fifo_0/design_1_s03_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s04_data_fifo_0/design_1_s04_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2}] {/inst }]/inst ]]

# XDC: bd/design_1/design_1_ooc.xdc
