#ifndef TRIGGER_LOGIC_H
#include "xil_io.h"
#define trigger_logic_wrReg(AXI_ADR,S_ADR,VAL)	 Xil_Out32(AXI_ADR+S_ADR*4,VAL)

#define trigger_logic_rdReg(AXI_ADR,S_ADR)	 Xil_In32(AXI_ADR+S_ADR*4)

#define TRIGGER_LOGIC_DELAY_0	0
#define	TRIGGER_LOGIC_DELAY_RESET	16
#define TRIGGER_LOGIC_COIN_ENABLE	18
#define TRIGGER_LOGIC_PRESCALER_ADR	19
#define TRIGGER_LOGIC_PRESCALER_DELAY	20
#define TRIGGER_LOGIC_PULSER_DIVISOR	21
#define	TRIGGER_LOGIC_PULSER_DUTY	22
#define	TRIGGER_LOGIC_PULSER_DELAY	23
#define	TRIGGER_LOGIC_ENABLES		24
#define	TRIGGER_LOGIC_HANDSHAKE_MASK	25
#define	TRIGGER_LOGIC_HANDSHAKE_DELAY	26
//#define	TRIGGER_LOGIC_HANDSHAKE_DELAY_MULT	27
#define TRIGGER_LOGIC_COIN_EDGE_HOLD	27
#define TRIGGER_LOGIC_COIN_PULSE_WIDTH  28
#define TRIGGER_LOGIC_OUTPUT_MUX_SELECT  29
#define TRIGGER_LOGIC_OUTPUT_DELAYS_12  30
#define TRIGGER_LOGIC_OUTPUT_DELAYS_3  31

//read back reg def
#define TRIGGER_LOGIC_EN_READBACK 48

#define TRIGGER_LOGIC_AXI_ADR 0x44A00000
#endif
