webtalk_init -webtalk_dir /data1/jmoore/XAPP1026/AC701_AxiEth_100Mhz_64kb/HW/project_1.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan  5 12:40:34 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1266856" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210387106_200942268_210590632_005" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9a34d985-8dad-4595-82a3-1b9881ce6b89" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bcf93235-5534-44a6-8ba6-e666ed1466e1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "39" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ScientificCERNSLC" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Scientific Linux CERN SLC release 6.7 (Carbon)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           E5420  @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2000.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Digilent/JTAG-SMT1/15000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13636093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:01:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cfgmem -value "n25q256-3.3v-spi-x1_x2_x4" -context "labtool\\usage"
webtalk_transmit -clientid 3105580310 -regid "210387106_200942268_210590632_005" -xml /data1/jmoore/XAPP1026/AC701_AxiEth_100Mhz_64kb/HW/project_1.hw/webtalk/usage_statistics_ext_labtool.xml -html /data1/jmoore/XAPP1026/AC701_AxiEth_100Mhz_64kb/HW/project_1.hw/webtalk/usage_statistics_ext_labtool.html -wdm /data1/jmoore/XAPP1026/AC701_AxiEth_100Mhz_64kb/HW/project_1.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
